#!/usr/bin/env python3
"""Expand a seed list of modules into a complete, dependency-ordered load list.

Android's first-stage init relies on modprobe, and its 83-entry list only works
because modprobe pulls dependencies in. The e5-linux initramfs loads modules with
insmod (a flat, deterministic order, which is what makes the stock ordering
constraint survivable), so the dependency closure has to be computed here.

Reads a modules.dep generated by depmod, starts from the seed list, pulls in
every dependency, and prints the result in dependency-first order.

usage: gen-module-order.py modules.dep seed1.txt [seed2.txt ...]
"""
import sys
from pathlib import Path


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    dep_path = Path(sys.argv[1])
    seeds = []
    for f in sys.argv[2:]:
        for raw in Path(f).read_text().splitlines():
            line = raw.split('#', 1)[0].strip()
            if line:
                seeds.append(line)
    seeds = list(dict.fromkeys(seeds))

    deps = {}
    present = set()
    for line in dep_path.read_text().splitlines():
        if not line.strip():
            continue
        left, _, right = line.partition(':')
        mod = left.strip()
        present.add(mod)
        deps[mod] = [d for d in right.split() if d]

    by_base = {}
    for m in present:
        by_base.setdefault(Path(m).name, m)

    ordered = []
    seen = set()
    missing = []

    def visit(mod, stack):
        if mod in seen:
            return
        if mod in stack:
            # dependency cycle: break it rather than recursing forever
            return
        stack.add(mod)
        for d in deps.get(mod, []):
            visit(d, stack)
        stack.discard(mod)
        seen.add(mod)
        ordered.append(mod)

    for s in seeds:
        full = by_base.get(s, s)
        if full not in present:
            missing.append(s)
            continue
        visit(full, set())

    for m in ordered:
        print(Path(m).name)
    if missing:
        print('not built (skipped): %s' % ' '.join(missing), file=sys.stderr)


if __name__ == '__main__':
    main()
