#!/bin/sh /etc/rc.common
# Two-SIM SMS: source-labelled inbox, alerts and forwards from SIPC events.
START=80
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/e5-sms-notify
	procd_set_param respawn 3600 5 0
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}
